version: '3.8'

services:
  db:
    container_name: mongo_marvel_db
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: marvel
    volumes:
      - ./mongo:/data/db
